services:
    app:
        container_name: full_app
        build: .
        restart: on-failure
        env_file:
            - .env
        volumes:
            - .:/usr/src/app/
        depends_on:
            - db
        ports:
            - "8080:8080"
        networks:
            - stack
    db:
        image: postgres
        volumes:
            - ./Docker/data:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - DATABASE_HOST=${DB_HOST}
        ports:
            - "5433:5432"
        networks:
            - stack
# Networks to be created to facilitate communication between containers
networks:
    stack:
        driver: bridge
