services:
   db:
        image: postgres
        environment:
            - POSTGRES_USER=${TEST_DB_USER}
            - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
            - POSTGRES_DB=${TEST_DB_NAME}
            - DATABASE_HOST=${TEST_DB_HOST}
        ports:
            - "5432:5432"
