services:
    postgres-dvdrental:
        image: postgres
        hostname: dvdrental-db
        volumes:
            - ./data:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - DATABASE_HOST=${DB_HOST}
        ports:
            - "5433:5432"
        